services:
  - type: web
    name: n8n-service
    env: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/n8n-io/n8n.git # This will use the official n8n repo
    healthCheckPath: /healthz
    envVars:
      - key: N8N_HOST
        fromService:
          type: web
          name: n8n-service
          property: host
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        fromService:
          type: pserv
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_HOST
        fromService:
          type: pserv
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PASSWORD
        fromService:
          type: pserv
          name: n8n-db
          property: password
      - key: DB_POSTGRESDB_USER
        fromService:
          type: pserv
          name: n8n-db
          property: user
  - type: pserv
    name: n8n-db
    env: postgres
    disk:
      name: n8n-data
      sizeGB: 1
